### ISSUE TITLE
Why has my affiliation been changed without my knowledge

### ISSUE THREAD

**Issue by jmhbnz** [cncf/gitdm#388]
I originally added my affiliation in https://github.com/cncf/gitdm/pull/11/files.

Subsequently this pr has been merged which has added garbage data https://github.com/cncf/gitdm/commit/ad9449e150930d734e3aee16eb84979589f69cd9#diff-ba7be0b9987ea363432bffb3c63f8336da54137c22bf204fb71fd028ca3cda0a.

The diff for my github user is:

```diff
jmhbnz: jmhbnz!users.noreply.github.com, mail!jamesblair.net
-	Independent until 2022-09-01
-	Red Hat Inc. from 2022-09-01
+	Red Hat Inc. until 2020-12-01
+	Independent from 2020-12-01 until 2022-09-01
+	Acme Gating from 2022-09-01
```

The new data is totally incorrect and was made without my knowledge, I still work at Red Hat. Why has it been changed?  There are potentially others impacted.

**Comment by jmhbnz** [comment]
cc @lukaszgryglicki - Depending how widespread this could be significantly impacting future reporting based on the data in this repository.

**Comment by lukaszgryglicki** [comment]
I'll take a look on Friday, should I change it back to:
```
-	Independent until 2022-09-01
-	Red Hat Inc. from 2022-09-01
```
?

**Comment by jmhbnz** [comment]
> I'll take a look on Friday, should I change it back to:
> 
> ```
> -	Independent until 2022-09-01
> -	Red Hat Inc. from 2022-09-01
> ```


Thank you for looking into this. Yes the original values should be restored.

My concern is that there could be many others also impacted. You might want to compare how many people were set to `Acme Gating` after the linked pr versus beforehand to check how widespread the incorrect updates could be.

**Comment by lukaszgryglicki** [comment]
Hi, I'm updating this, but I cannot guess if other affiliations are good or bad, we had a bunch of updates from one data file to by in sync with another, that could cause this (I'm sorry) - we will no longer do this - this was done due to a bug fixing.
Now we are researching new, unknown yet and having done their 1st time contribution to any CNCF project, so it won't be changing any existing affiliations.

Right now I'll change back your affiliation to what it was before.

**Comment by lukaszgryglicki** [comment]
Updated, closing this, please reopen if needed.
